version: 2

project_name: certwatch-webhook-cli

builds:
  - main: .
    binary: certwatch-webhook-cli
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^ci:'
      - '^chore:'

brews:
  - repository:
      owner: certwatch-app
      name: homebrew-tap
    homepage: https://certwatch.app
    description: Deliver real CT certificate webhook payloads to your local endpoint
    license: MIT
    install: |
      bin.install "certwatch-webhook-cli"
